apiVersion: v1
kind: Service
metadata:
  name: {{ include "alert-center.fullname" . }}-admin
  labels:
    {{- include "alert-center.labels" . | nindent 4 }}
    app.kubernetes.io/component: admin
spec:
  type: ClusterIP
  ports:
    - port: 8002
      targetPort: 8002
      protocol: TCP
  selector:
    {{- include "alert-center.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: admin
